// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clarifin-variants/BoldDark.tsx": () => import("../components/mockups/clarifin-variants/BoldDark.tsx"),
  "./components/mockups/clarifin-variants/CalmMinimal.tsx": () => import("../components/mockups/clarifin-variants/CalmMinimal.tsx"),
  "./components/mockups/clarifin-variants/VibrantFintech.tsx": () => import("../components/mockups/clarifin-variants/VibrantFintech.tsx"),
  "./components/mockups/clarifin-variants/WarmFriendly.tsx": () => import("../components/mockups/clarifin-variants/WarmFriendly.tsx")
};
