// AUTO-GENERATED — do not edit by hand.
// Generated by scripts/generate-html-module.mjs after the Vite build.
// This placeholder is overwritten during `vercel build` / local build.
export const indexHtml = "<!DOCTYPE html><html><body>Building...</body></html>";
